---
abstract: "[One line description of module's purpose here]"
author:
  - 'Kevin Falcone <falcone@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-SpawnLinkedTicketInQueue
no_index:
  directory:
    - html
    - inc
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01_01
